import QtQuick 2.0

// Note that this font is generated by uploading a couple of svgs
// from the font to fontello, then downloading the zip and using the ttf.
// We can then use these icons anywhere, in any color.
FontLoader {
	id: octicons
	source: "../fonts/fontello.ttf"
	readonly property string comment: "\ue800"
	readonly property string issueClosed: "\ue801"
	readonly property string issueOpened: "\ue802"
	readonly property string markGithub: "\ue803"
	readonly property string repo: "\ue804"
	readonly property string gitMerge: "\ue805"
	readonly property string gitPullRequest: "\ue806"
}
