position: "top"
height: 28
popup_gap: 5
margin.top: 0
margin.bottom: 0
margin.left: 0
margin.right: 0
icon_theme: "Papirus"

start: 
  - type: "workspaces"
    icon_size: 26
    sort: 'name'
    name_map:
      "1": "一"
      "2": "二"
      "3": "三"
      "4": "四"
      "5": "五"
      "6": "六"
      "7": "七"
      "8": "八"
      "9": "九"
      "10": "十"

  - type: "tray"
    icon_size: 16

  - type: "focused"
    show_icon: false
    icon_size: 26
    max_length: 30
    truncate: "end"

end: 
  - type: "sys_info"
    format: 
      - '  {cpu_percent}%'
      - ' {temp_c:coretemp-Package-id-0}°C  '
      - '  {memory_used:} GB ({memory_percent}%) '
      - '󰋊  {disk_used:/} GB ({disk_percent:/}%)'
      - '󰓢 {net_up:wlp1s0} / {net_down:wlp1s0} MiB/s'
    interval: 
      cpu: 5
      disks: 900
      memory: 60
      networks: 5
      temps: 15

  - type: "volume"
    format: "{icon}  {percentage}%"
    max_volume: 140
    icons:
      volume_high: "󰕾 "
      volume_medium: "󰖀 "
      volume_low: "󰕿"
      muted: "󰝟 "

  - type: "notifications"
    show_count: true
    icons:
      closed_none: 󰍥
      closed_some: 󱥂
      closed_dnd: 󱅯
      open_none: 󰍡
      open_some: 󱥁
      open_dnd: 󱅮

  - type: "upower"
    format: "{percentage}%"

  - type: "clock"
    format: "   %Y-%m-%d  %H:%M"
